<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Outil de synchronisation de l\'horloge et du fuseau horaire.';
$lang['date_app_name'] = 'Date and Time';
$lang['date_app_tooltip'] = 'La VoIP, les services d\'authentification et d\'autres applications nécessitent des réglages appropriés de l\'heure, aussi veuillez vérifier que l\'heure et le fuseau horaire sont corrects!';
$lang['date_automatic_synchronize'] = 'Automatic Synchronize';
$lang['date_date'] = 'Date';
$lang['date_synchronize'] = 'Synchroniser';
$lang['date_synchronize_help'] = 'Cliquer le bouton Synchroniser pour mettre à jour l\'horloge système à l\'heure correcte.  Votre système synchronisera automatiquement son horloge régulièrement.';
$lang['date_synchronize_now'] = 'Synchroniser maintenant';
$lang['date_synchronized'] = 'Synchronisé';
$lang['date_synchronizing'] = 'Synchronisation en cours';
$lang['date_time'] = 'Heure';
$lang['date_time_server'] = 'Serveur de temps';
$lang['date_time_server_is_invalid'] = 'Le serveur de temps n\'est pas valide.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'La planification de la synchronisation n\'est pas valide.';
$lang['date_time_zone'] = 'Fuseau horaire';
$lang['date_time_zone_is_invalid'] = 'Le fuseau horaire n\'est pas valide.';
$lang['date_time_zone_wizard_help'] = 'De nombreuses applications et services nécessitent une information de zone horaire correcte ainsi qu\'une horloge précise, il est donc important de les paramétrer correctement.';
