<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Часовой пояс и инструмент синхронизации часов.';
$lang['date_app_name'] = 'Дата и время';
$lang['date_app_tooltip'] = 'VoIP, службы аутентификации и другие приложения требуют надлежащих параметров настройки времени, таким образом, удостоверяются, что ваши часы и часовой пояс корректны!';
$lang['date_automatic_synchronize'] = 'Автоматическая синхронизация';
$lang['date_date'] = 'Дата';
$lang['date_synchronize'] = 'Синхронизация';
$lang['date_synchronize_now'] = 'Синхронизируйтесь теперь';
$lang['date_synchronized'] = 'Синхронизировано';
$lang['date_synchronizing'] = 'Синхронизируюсь';
$lang['date_time'] = 'Время';
$lang['date_time_server'] = 'Сервер Времени';
$lang['date_time_server_is_invalid'] = 'Сервер времени является недействительным.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Время расписание синхронизации является недействительным.';
$lang['date_time_zone'] = 'Часовой пояс';
$lang['date_time_zone_is_invalid'] = 'Часовой пояс является недействительным.';
$lang['date_time_zone_wizard_help'] = 'Много приложений и служб запрашивают корректную информацию часового пояса и точные часы, таким образом, важно, чтобы это было установлено правильно.';
