<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Zona waktu dan alat sinkronisasi.';
$lang['date_app_name'] = 'Date and Time';
$lang['date_app_tooltip'] = 'VoIP, layanan otentikasi dan aplikasi lainya membutuhkan pengaturan waktu yang tepat, jadi silahkan cek kembali waktu anda dan zona waktu yang benar!';
$lang['date_date'] = 'Tanggal';
$lang['date_synchronize'] = 'Synchronize';
$lang['date_synchronize_help'] = 'Click on the synchronize button to update the system clock with the correct time.  Your system will automatically synchronize its clock from time to time.';
$lang['date_synchronize_now'] = 'Sinkronisasikan Sekarang';
$lang['date_synchronized'] = 'Synchronized';
$lang['date_synchronizing'] = 'Synchronizing';
$lang['date_time'] = 'Waktu';
$lang['date_time_server'] = 'Server Waktu';
$lang['date_time_server_is_invalid'] = 'Server Waktu tidak benar.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Jadwal waktu sinkronisasi tidak benar.';
$lang['date_time_zone'] = 'Zona Waktu';
$lang['date_time_zone_is_invalid'] = 'Zona waktu tidak benar.';
$lang['date_time_zone_wizard_help'] = 'Many apps and services require correct time zone information and an accurate clock, so it is important that it is set correctly.';
