<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Das Zeitzonen und Zeitsynchronisierungstool.';
$lang['date_app_name'] = 'Tag und Uhrzeit';
$lang['date_app_tooltip'] = 'VoIP, Anmeldedienste und weitere Anwendungen benötigen eine korrekte Zeiteinstellung. Stellen Sie daher sicher, dass die Zeit und Zeitzone korrekt ist!';
$lang['date_automatic_synchronize'] = 'Automatic Synchronize';
$lang['date_date'] = 'Date';
$lang['date_synchronize'] = 'Synchronisieren';
$lang['date_synchronize_help'] = 'Klicken Sie auf den Synchronisieren Button um Ihr System mit der korrekten Uhrzeit zu synchronisieren.  Ihr System wird von Zeit zu Zeit die Uhrzeit automatisch aktualisieren.';
$lang['date_synchronize_now'] = 'Jetzt Synchronisieren';
$lang['date_synchronized'] = 'Synchronisiert';
$lang['date_synchronizing'] = 'Wird Synchronisiert';
$lang['date_time'] = 'Zeit';
$lang['date_time_server'] = 'Zeitserver';
$lang['date_time_server_is_invalid'] = 'Zeitserver ist ungültig.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Zeitplan für die Zeitsynchroniserung ist ungültig.';
$lang['date_time_zone'] = 'Zeitzone';
$lang['date_time_zone_is_invalid'] = 'Zeitzone ist ungültig.';
$lang['date_time_zone_wizard_help'] = 'Viele Apps und Dienste benötigen die korrekte Zeitzone und die genaue Uhrzeit. Daher ist es wichtig dies korrekt zu setzen.';
