<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Zeit- und Zeitzonen Verwaltung.';
$lang['date_app_name'] = 'Datum und Uhrzeit';
$lang['date_app_tooltip'] = 'VoIP, Authentifizierungsdienste sowie andere Applikationen benötigen eine richtig eingestellte Uhrzeit. Bitte stellen Sie sicher, dass Zeit und Zeitzone korrekt sind!';
$lang['date_automatic_synchronize'] = 'Automatisch Synchronisieren';
$lang['date_date'] = 'Datum';
$lang['date_synchronize'] = 'Synchronisieren';
$lang['date_synchronize_now'] = 'Jetzt Synchronisieren';
$lang['date_synchronize_wizard_tip'] = 'With automatic synchronize enabled, the system will synchronize its clock from time to time.';
$lang['date_synchronized'] = 'Synchronisiert';
$lang['date_synchronizing'] = 'Wird Synchronisiert';
$lang['date_time'] = 'Zeit';
$lang['date_time_server'] = 'Zeitserver';
$lang['date_time_server_is_invalid'] = 'Zeitserver ist ungültig.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Zeitplan für die Zeitsynchroniserung ist ungültig.';
$lang['date_time_zone'] = 'Zeitzone';
$lang['date_time_zone_is_invalid'] = 'Zeitzone ist ungültig.';
$lang['date_time_zone_wizard_help'] = 'Viele Apps und Dienste benötigen die korrekte Zeitzone und die genaue Uhrzeit. Daher ist es wichtig dies korrekt zu setzen.';
