<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Ferramenta de Fuso Horário e Sincronização do relógio.';
$lang['date_app_name'] = 'Data e Hora';
$lang['date_app_tooltip'] = 'VoIP, serviço de autenticação e outras aplicações exigem configurações de tempo adequados, por isso, verifique se o seu relógio e o fuso horário estão corretos!';
$lang['date_date'] = 'Data';
$lang['date_synchronize'] = 'Sincronizar';
$lang['date_synchronize_now'] = 'Sincronizar Agora';
$lang['date_synchronized'] = 'Sincronizado';
$lang['date_synchronizing'] = 'Sincronizando';
$lang['date_time'] = 'Hora';
$lang['date_time_server'] = 'Servidor de Hora';
$lang['date_time_server_is_invalid'] = 'Servidor de Hora Inválido.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Agendamento da Sincronização de Hora inválido.';
$lang['date_time_zone'] = 'Fuso Horário';
$lang['date_time_zone_is_invalid'] = 'Fuso Horário Inválido.';
$lang['date_time_zone_wizard_help'] = 'Muitos aplicativos e serviços exigem informações de fuso horário correto e um relógio preciso, por isso é importante que ele esteja configurado corretamente.';
