<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'အခ်ိန္ဇံုနွင္႔ နာရီခ်ိန္ကိုက္မွဳကိရိယာတန္ဆာ';
$lang['date_app_name'] = 'ေန႔ရက္ႏွင္႔ အခ်ိန္';
$lang['date_app_tooltip'] = 'VoIP, authentication services ႏွင္႔ အျခားေသာ applications တို႔သည္ သင္႔ေတာ္ေသာ အခ်ိန္ကိုက္ညွိမွဳလိုအပ္ေသာေၾကာင္႔ နာရီနွင္႔ အခ်ိန္ဇံုမ်ားကို ေသခ်ာမွန္ကန္မွုရွိေအာင္ျပဳလုပ္ပါ။';
$lang['date_automatic_synchronize'] = 'Automatic Synchronize';
$lang['date_date'] = 'ေန႔ရက္';
$lang['date_synchronize'] = 'ခ်ိန္ကိုက္';
$lang['date_synchronize_now'] = 'ယခုပဲ ခ်ိန္ကိုက္မွဳျပဳလုပ္ပါ။';
$lang['date_synchronize_wizard_tip'] = 'With automatic synchronize enabled, the system will synchronize its clock from time to time.';
$lang['date_synchronized'] = 'ခ်ိန္ကိုက္ျပီး';
$lang['date_synchronizing'] = 'ခ်ိန္ကိုက္မွဳျပဳလုပ္ေနသည္';
$lang['date_time'] = 'အခ်ိန္';
$lang['date_time_server'] = 'အခ်ိန္ဆာဗာ';
$lang['date_time_server_is_invalid'] = 'အခ်ိန္ဆာဗာ အတည္ျပဳ၍မရပါ';
$lang['date_time_synchronization_schedule_is_invalid'] = 'အခ်ိန္ကိုက္ညွိျခင္း အစီအစဥ္မွားယြင္းေနသည္။';
$lang['date_time_zone'] = 'အခ်ိန္နယ္ေျမဇံု';
$lang['date_time_zone_is_invalid'] = 'အခ်ိန္နယ္ေျမဇံု မွားယြင္းေနသည္။';
$lang['date_time_zone_wizard_help'] = 'Apps ႏွင္႔ Services အမ်ားစုသည္ မွန္ကန္ေသာ အခ်ိန္ဇံုအခ်က္အလက္နွင္႔ တိက်ေသာ နာရီကိုက္ညွိမွဳလိုအပ္ေသာေၾကာင္႔ မွန္မွန္ကန္ကန္ တိုက္ညွိထားဖို႔လိုအပ္ပါသည္။';
