<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Tidszon och synkronisering av klockan.';
$lang['date_app_name'] = 'Datum och tid';
$lang['date_app_tooltip'] = 'VOIP, autentisieringstjänster och andra applikationer kräver noggranna tidsangivelser, var därför noggrann med att din klocka och tidszon är korrekta!';
$lang['date_automatic_synchronize'] = 'Automatisk synkronisering';
$lang['date_date'] = 'Datum';
$lang['date_synchronize'] = 'Synkronisera';
$lang['date_synchronize_now'] = 'Synkronisera nu';
$lang['date_synchronize_wizard_tip'] = 'With automatic synchronize enabled, the system will synchronize its clock from time to time.';
$lang['date_synchronized'] = 'Synkroniserad';
$lang['date_synchronizing'] = 'Synkroniserar';
$lang['date_time'] = 'Klockslag';
$lang['date_time_server'] = 'Tidsserver';
$lang['date_time_server_is_invalid'] = 'Tidsservern är ogiltig.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Schemat för tidssynkronisering är ogiltigt.';
$lang['date_time_zone'] = 'Tidszon';
$lang['date_time_zone_is_invalid'] = 'Tidszonen är ogiltig.';
$lang['date_time_zone_wizard_help'] = 'Många appa och tjänster kräver en korrekt tidszon och en korrekt klocka, så det är viktigt att inställningarna är korrekta.';
