<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'De tijdzone en de klok synchronisatie gereedschap.';
$lang['date_app_name'] = 'Datum en tijd';
$lang['date_app_tooltip'] = 'VoIP, authenticatie services en andere toepassingen vereisen de juiste tijd instellingen, dus zorg ervoor dat uw klok en tijdzone correct zijn!';
$lang['date_automatic_synchronize'] = 'Automatic Synchronize';
$lang['date_date'] = 'Datum';
$lang['date_synchronize'] = 'Synchronize';
$lang['date_synchronize_help'] = 'Click on the synchronize button to update the system clock with the correct time.  Your system will automatically synchronize its clock from time to time.';
$lang['date_synchronize_now'] = 'Synchroniseren';
$lang['date_synchronized'] = 'Synchronized';
$lang['date_synchronizing'] = 'Synchronizing';
$lang['date_time'] = 'Tijd';
$lang['date_time_server'] = 'Tijd server';
$lang['date_time_server_is_invalid'] = 'Ongeldige tijdserver.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Ongeldig tijd synchronisatie schema. ';
$lang['date_time_zone'] = 'Tijdzone';
$lang['date_time_zone_is_invalid'] = 'Ongeldige tijdzone.';
$lang['date_time_zone_wizard_help'] = 'Many apps and services require correct time zone information and an accurate clock, so it is important that it is set correctly.';
