<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'Narzędzie do zmiany strefy czasowej i synchronizacji czasu.';
$lang['date_app_name'] = 'Date and Time';
$lang['date_app_tooltip'] = 'VoIP, usługi uwierzytelniania oraz inne aplikacje wymagają poprawnego ustawienia czasu, więc prosimy upewnić się, że zegar i strefa czasowa są prawidłowe!';
$lang['date_automatic_synchronize'] = 'Synchronizacja automatyczna';
$lang['date_date'] = 'Data';
$lang['date_synchronize'] = 'Synchronizuj';
$lang['date_synchronize_help'] = 'Kliknij na przycisk synchronizacji aby uaktualnić zegar systemowy na prawidłowy czas.  Twój system będzie automatycznie aktualizował zegar systemowy od czasu do czasu.';
$lang['date_synchronize_now'] = 'Synchronizuj';
$lang['date_synchronized'] = 'Zsynchronizowane';
$lang['date_synchronizing'] = 'Synchronizuję';
$lang['date_time'] = 'Czas';
$lang['date_time_server'] = 'Serwer czasu';
$lang['date_time_server_is_invalid'] = 'Podana nazwa serwera czasu jest nieprawidłowa.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Harmonogram synchronizacji czasu jest nieprawidłowy.';
$lang['date_time_zone'] = 'Strefa czasowa';
$lang['date_time_zone_is_invalid'] = 'Podana nazwa strefy czasowej jest nieprawidłowa.';
$lang['date_time_zone_wizard_help'] = 'Wiele aplikacji i usług wymaga prawidłowych informacji na temat strefy czasowej oraz zegara, więc ważne jest prawidłowe ich ustawienie.';
