<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['date_app_description'] = 'The time zone and clock synchronization tool.';
$lang['date_app_name'] = 'Petsa at Oras';
$lang['date_app_tooltip'] = 'VoIP, authentication services and other applications require proper time settings, so please make sure your clock and time zone are correct!';
$lang['date_date'] = 'Petsa';
$lang['date_synchronize'] = 'Synchronize';
$lang['date_synchronize_help'] = 'Click on the synchronize button to update the system clock with the correct time.  Your system will automatically synchronize its clock from time to time.';
$lang['date_synchronize_now'] = 'Maayos ang oras';
$lang['date_synchronized'] = 'Synchronized';
$lang['date_synchronizing'] = 'Synchronizing';
$lang['date_time'] = 'Oras';
$lang['date_time_server'] = 'Time Server';
$lang['date_time_server_is_invalid'] = 'Time server is invalid.';
$lang['date_time_synchronization_schedule_is_invalid'] = 'Time synchronization schedule is invalid.';
$lang['date_time_zone'] = 'Time Zone';
$lang['date_time_zone_is_invalid'] = 'Time zone is invalid.';
$lang['date_time_zone_wizard_help'] = 'Many apps and services require correct time zone information and an accurate clock, so it is important that it is set correctly.';
